version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - newman/newman-run:
         collection: ./tests/METestColl.json
         environment: /tests/METestEnv.postman_environment.json
         timeout: '3000'
